### PR TITLE
Updated template to include SPC option and digital signature

### LINKED ISSUE #97: Digital signatures on template
As a DS, I want to have digital signatures for AF initials, so that the AC commander can sign electronically during the in-brief

### PR DESCRIPTION
**Pull request by mjennings061**
Closes #97, #91 

Go to `docs/2965D_YYMMDD_ZEXXX.xltx` and have a play to:
1. Check if changing the SPC works during soaring
2. Check if changing SPC works during aeros
3. Enter the last four of your service number into AF initials. See the initials appear in the "Print Copy" sheet. **Enter 1234 because SNs have been removed in the template for privacy**

### CODE REVIEW

**Review by DAbbott99 — CHANGES_REQUESTED** [review]
Aeros and Soaring tick boxes are within protected cells. Will need unprotected as to allow selection before merging.

SPC changes as expected without issue. But before further roll out to wider 2FTS the option for all 7 SPCs to be inputted would need to be added (i.e Aerotow)

A/F initials work as expected no issue. Will be an easy fix but has how those without service numbers use this system been disscussed?

**Comment by mjennings061** [comment]
@DAbbott99 amazing suggestions, thank you!

> Aeros and Soaring tick boxes are within protected cells. Will need unprotected as to allow selection before merging.
Doh 🤦‍♂️ I updated this now

> SPC changes as expected without issue. But before further roll out to wider 2FTS the option for all 7 SPCs to be inputted would need to be added (i.e Aerotow). This can still be a down the line fix so doesn't prevent merging
Yep that would need the 2965A, so would be a new document altogether. I am content this is out of scope of this pull request

> A/F initials work as expected no issue. Will be an easy fix but has how those without service numbers use this system been disscussed?
That would require a wet signature. We have to get a wet signature from the DS anyway but at least this method stops us chasing half the squadron each day.

**Comment by DAbbott99** [comment]
Last Q @mjennings061 (playing devils advocate because I do like the idea) to do with the A/F how about visitors? The example I think which started all this was Gary on CFS he would want to sign then and there rather than wait until printed but then not being on the list he wouldn't be able to use a pin.

**Review by DAbbott99 — APPROVED** [review]

**Comment by mjennings061** [comment]
> Last Q @mjennings061 (playing devils advocate because I do like the idea) to do with the A/F how about visitors? The example I think which started all this was Gary on CFS he would want to sign then and there rather than wait until printed but then not being on the list he wouldn't be able to use a pin.

Had a chat with JB. We will add visitors to the INPUT_DATA sheet when they arrive. They can also sign the physical copy so all is well

**Pull request merged**
