### PR TITLE
Use keyring to store credentials. Added Config dataclass

### LINKED ISSUE #36: Store credentials using keyring
As a user, I want to store my credentials via keyring, so that they persist when I update the package

### PR DESCRIPTION
**Pull request by mjennings061**
Closes #36

### CODE REVIEW

**Comment by mjennings061** [comment]
@CameronMacG and @dgscwhite I need your assistance reviewing this please. Can you do the following to test this works:

1. Clone the repo (if you have not already)

```bash
git clone https://github.com/mjennings061/viking-log-keeper.git
```

2. Navigate into the directory:

```bash
cd viking-log-keeper
```

3. Install the app (ensure you have python installed). The `.` is important below

```bash
python -m pip install --upgrade .
```

4. Run the dashboard

```bash
viking-dashboard
```

5. Enter in the database credentials from your email (it will auto prompt you)
6. Go to the dashboard [http://localhost:8501](http://localhost:8501)

**Comment by DAbbott99** [comment]
Running `viking-dashboard` gives the following error:

```bash
PS C:\Users\Daniel\viking-log-keeper> viking-dashboard
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python311\Scripts\viking-dashboard.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'dashboard'
```

**Comment by mjennings061** [comment]
> Running `viking-dashboard` gives the following error:
> 
> ```shell
> PS C:\Users\Daniel\viking-log-keeper> viking-dashboard
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python311\Scripts\viking-dashboard.exe\__main__.py", line 4, in <module>
> ModuleNotFoundError: No module named 'dashboard'
> ```

Thank you for reviewing so quickly @DAbbott99. I will have a look today to see if I can debug that. Good to see the `update-logs` is working better for you

**Comment by mjennings061** [comment]
@DAbbott99 Can you pretty please open powershell and run the following?

```bash
cd viking-log-keeper
git pull
python -m pip install --upgrade .
viking-dashboard
```

**Comment by DAbbott99** [comment]
> ```shell
> cd viking-log-keeper
> git pull
> python -m pip install --upgrade .
> viking-dashboard
> ```

**Review by DAbbott99 — APPROVED** [review]
Works

**Pull request merged**
