### PR TITLE
49 separate streamlit from update logs

### LINKED ISSUE #49: Separate streamlit from `update-logs`
As a user, I want to `update-logs` without requirement for streamlit, so that I can avoid the bug below:

image

### PR DESCRIPTION
**Pull request by mjennings061**
Closes #49

### CODE REVIEW

**Comment by mjennings061** [comment]
Reviewers, can you please test this tonight? Run the following in terminal, from the viking-log-keeper folder:

```bash
git fetch origin
git checkout 49-separate-streamlit-from-update-logs
python -m pip install --upgrade .
update-logs
```

**Comment by dgscwhite** [comment]
Tested the code.  Recieved the following error when running the command update-logs:                                        
INFO:log_keeper.main:Starting...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python311\Scripts\update-logs.exe\__main__.py", line 7, in <module>
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\log_keeper\main.py", line 46, in main
    auth_config = AuthConfig()
                  ^^^^^^^^^^^^
  File "<string>", line 14, in __init__
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\dashboard\auth.py", line 46, in __post_init__
    self.load_secrets()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python311\Lib\site-packages\dashboard\auth.py", line 62, in load_secrets
    self.auth_url = self.auth_url.replace(
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not None

**Comment by dgscwhite** [comment]
Code ran successfully.  This time I was asked to enter my credentials when I ran the code 'update-logs'.

**Review by dgscwhite — APPROVED** [review]
Code checked and working.

**Pull request merged**
